version: "3.8"
services:
    java-maven-app:
      image: zhajili/my_aws_app:1.7
      ports:
        - 3001:8080
    postgres:
      image: postgres
      ports:
        - 5433:5432
      environment:
        - POSTGRES_PASSWORD=Krakow123