version: '3'
services:
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=zhajili
     - MONGO_INITDB_ROOT_PASSWORD=Krakow123
  mongo-express:
    image: mongo-express
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=zhajili
     - ME_CONFIG_MONGODB_ADMINPASSWORD=Krakow123
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"
