version: '3'
services:
  my_flask_app:
    image: public.ecr.aws/e4m9k3i5/my_flask_app:1.3
    ports:
     - 3000:3000
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=zhajili
     - MONGO_INITDB_ROOT_PASSWORD=Krakow123
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=zhajili
     - ME_CONFIG_MONGODB_ADMINPASSWORD=Krakow123
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"
volumes:
  mongo-data:
    driver: local
