pipeline {
    agent any
    stages {
        stage('Welcome Step') {
            steps {
                echo 'Welcome to JenkinsTest'
            }
        }
        stage('Building Step') {
            steps {
                echo 'Building App'
            }
        }
        stage('Testing Step') {
            steps {
                echo 'Testing App'
            }
        }
        stage('Deploying Step') {
            steps {
                echo 'Deploy the App'
            }
        }
    }
}