pipeline {
    agent any
    tools {
        maven 'maven-3.6'
    }
    stages {
        stage('Incrementing App Version') {
            steps {
                script {
                    echo 'incrementing app version...'
                    sh 'mvn build-helper:parse-version versions:set \
                        -DnewVersion=\\\${parsedVersion.majorVersion}.\\\${parsedVersion.minorVersion}.\\\${parsedVersion.nextIncrementalVersion} \
                        versions:commit'
                    def matcher = readFile('pom.xml') =~ '<version>(.+)</version>'
                    def version = matcher[0][1]
                    env.IMAGE_NAME = "$version-$BUILD_NUMBER"
                        }
            }
        }
        stage('Building application') {
            steps {
                script {
                    echo "building the application..."
                    sh 'mvn clean package'
                }
            }
        }
        stage('building docker image') {
            steps {
                script {
                    echo 'Building Docker Image..!'
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-repo', passwordVariable: 'PASS', usernameVariable: 'USER' )])
                        {
                                sh "docker build -t zhajili/devops:${IMAGE_NAME} ."
                                sh "echo $PASS | docker login -u $USER --password-stdin"
                                sh "docker push zhajili/devops:${IMAGE_NAME}"
                        }
                }
            }
        }
       stage('commit version update') {
                   steps {
                       script {
                           withCredentials([usernamePassword(credentialsId: 'git-creds', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                               // git config here for the first time run
                               sh 'git config user.email "hacizeynal@hotmail.com"'
                               sh 'git config user.name "hacizeynal"'

                               sh "git remote set-url origin https://${USER}:${PASS}@github.com/zhajili91/DevOps_course.git"
                               sh 'git add .'
                               sh 'git commit -m "commit updates via Jenkins"'
                               sh 'git push origin HEAD:increment-app-maven'
                           }
                       }
                   }
               }
           }
        }